name: Build and Package

on:
  push:
    branches: 
      - main

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            runtime: win-x64
            artifact-name: h4d2-win-x64
            self-contained: true

          - os: windows-latest
            runtime: win-x86
            artifact-name: h4d2-win-x86
            self-contained: true

          - os: ubuntu-latest
            runtime: linux-x64
            artifact-name: h4d2-linux-x64
            self-contained: true

    env:
      DOTNET_NOLOGO: true
      CONFIGURATION: Release
      PROJECT_PATH: h4d2/h4d2.csproj
      PUBLISH_DIR: publish/${{ matrix.runtime }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x

      - name: Restore Dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Publish
        run: >
          dotnet publish ${{ env.PROJECT_PATH }}
          --no-restore
          --configuration ${{ env.CONFIGURATION }}
          --runtime ${{ matrix.runtime }}
          --self-contained ${{ matrix.self-contained }}
          -p:DebugSymbols=false
          --output ${{ env.PUBLISH_DIR }}

      - name: Install runtime dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y libopenal1
          sudo apt install -y libflac12
          sudo apt install -y libogg0
          sudo apt install -y libvorbis0a
          sudo apt install -y libvorbisenc2
          sudo apt install -y libvorbisfile3

      - name: Create AppDir (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p h4d2.AppDir/usr/bin
          cp -r ${{ env.PUBLISH_DIR }}/* h4d2.AppDir/usr/bin/

          cp /usr/lib/x86_64-linux-gnu/libopenal.so.1 h4d2.AppDir/usr/bin/
          cp /usr/lib/x86_64-linux-gnu/libflac.so.12 h4d2.AppDir/usr/bin/
          cp /usr/lib/x86_64-linux-gnu/libogg.so.0 h4d2.AppDir/usr/bin/
          cp /usr/lib/x86_64-linux-gnu/libvorbis.so.0 h4d2.AppDir/usr/bin/
          cp /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2 h4d2.AppDir/usr/bin/
          cp /usr/lib/x86_64-linux-gnu/libvorbisfile.so.3 h4d2.AppDir/usr/bin/

          cp cd/linux/AppRun h4d2.AppDir/
          chmod +x h4d2.AppDir/AppRun
          cp cd/linux/h4d2.desktop h4d2.AppDir/
          cp h4d2/Resources/executable_icons/linux/h4d2.png h4d2.AppDir/

      - name: Download appimagetool (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
   
      - name: Install FUSE (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo add-apt-repository universe
          sudo apt update
          sudo apt install -y libfuse2t64

      - name: Build AppImage (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          ARCH=x86_64 ./appimagetool-x86_64.AppImage h4d2.AppDir h4d2-linux-x64.AppImage

      - name: Upload build artifact (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ env.PUBLISH_DIR }}

      - name: Upload build artifact (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.artifact-name }}
          path: "h4d2-linux-x64.AppImage"
